### ISSUE TITLE
Options not showing when using reverse proxy

### ISSUE THREAD

**Issue by Johnpojohn** [YodaDaCoda/chrome-transmission-remote-plus#48]
Whenever I refer to my server ip directly (http://ip:someport/transmission), and save the settings, the extension works. If I open the options window again, everything shows up as I left it. However, if I refer to my nginx reverse proxy (https://someaddress:443/transmission) everything works, but the options screen is completely blank. The save button also stops reacting. Nevertheless, if Iwrite the direct ip again, everything works. Is this a chrome issue or an extension issue?

Thanks!

**Comment by wader** [comment]
Hi, when on the options page can you open the javascript console (View > Developer > JavaScript console) and see if there is any errors? if so paste them here

**Comment by Johnpojohn** [comment]
Yup

jquery-3.2.1.min.js:2 jQuery.Deferred exception: Cannot read property '1' of null TypeError: Cannot read property '1' of null
    at HTMLDocument.<anonymous> (chrome-extension://kfbocdnicmioodheiciijiegbmfoliim/js/options.js:201:28)
    at j (chrome-extension://kfbocdnicmioodheiciijiegbmfoliim/js/jquery-3.2.1.min.js:2:29999)
    at k (chrome-extension://kfbocdnicmioodheiciijiegbmfoliim/js/jquery-3.2.1.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery-3.2.1.min.js:2
jquery-3.2.1.min.js:2 Uncaught TypeError: Cannot read property '1' of null
    at HTMLDocument.<anonymous> (options.js:201)
    at j (jquery-3.2.1.min.js:2)
    at k (jquery-3.2.1.min.js:2)

**Comment by wader** [comment]
Looking at the code https://github.com/YodaDaCoda/chrome-transmission-remote-plus/blob/master/source/js/options.js#L201 i would guess it means that URL does not match the regex. Do you have any strange characters etc in the URL?

If you have problem changing it now you can probably change it by using `localStorage.server = "..."` in the javascript console on the options page and reload the page.

**Comment by Johnpojohn** [comment]
Hey,

well that part is fixed, the options now show properly and I can edit them. Now the issue is the opposite, the options are right but the connection in itself doesnt work. So:

http://ip:someport/transmission (with login, pasword, rpc and web subdirections) works
hpps://someaddress:443/transmission (same) doesnt

any way I could get this to work? What may be the issue?

Thanks!

**Comment by wader** [comment]
Hmm not sure, maybe check the network tab in developer console and check for failing requests?

**Comment by Johnpojohn** [comment]
Yup, Failed to load resource: the server responded with a status of 409 ()

**Comment by Johnpojohn** [comment]
It may have something to do with this:

409: Conflict
Your request had an invalid session-id header.

To fix this, follow these steps:

When reading a response, get its X-Transmission-Session-Id header and remember it
Add the updated header to your outgoing requests
When you get this 409 error message, resend your request with the updated header

**Comment by wader** [comment]
There is a 409 response? I think is already should be handling the session id header thing. It seems to work fine for me at least. I wonder if the URL ends up wrong i some way so it ends up talking to something else etc

**Comment by Johnpojohn** [comment]
Could be, any way that I could check that?
